# Generated by Django 5.1.15 on 2026-06-13 05:40

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0002_replace_icon_url_with_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamToolGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("icon_emoji", models.CharField(default="📁", max_length=8)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("orange", "Orange"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("amber", "Amber"),
                            ("teal", "Teal"),
                            ("stone", "Stone"),
                        ],
                        default="orange",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tool_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_groups",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("platform_key", models.CharField(default="custom", max_length=40)),
                ("url", models.URLField(max_length=500)),
                ("icon_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("cookies_json", apps.common.encryption.EncryptedTextField()),
                ("is_active", models.BooleanField(default=True)),
                ("session_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_temp_dir",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_team_tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_team_tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_tools",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, tool is public to all workspace members.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tools",
                        to="tools.teamtoolgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamToolGroupAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_tool_group_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="tools.teamtoolgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_group_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamToolUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("forced_return", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="tools.teamtool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_tool_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_tool_usage_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="teamtoolgroup",
            index=models.Index(
                fields=["workspace"], name="tools_teamt_workspa_aca71e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamtoolgroup",
            unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="teamtool",
            index=models.Index(
                fields=["workspace", "is_active"], name="tools_teamt_workspa_5a9f50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamtoolgroupaccess",
            index=models.Index(fields=["user"], name="tools_teamt_user_id_21aab2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamtoolgroupaccess",
            unique_together={("group", "user")},
        ),
        migrations.AddIndex(
            model_name="teamtoolusagelog",
            index=models.Index(
                fields=["workspace", "-started_at"],
                name="tools_teamt_workspa_a84563_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teamtoolusagelog",
            index=models.Index(
                fields=["tool", "-started_at"], name="tools_teamt_tool_id_68814b_idx"
            ),
        ),
    ]
