"""AI-powered caption generator for social media posts.

Supports Google Gemini and Anthropic Claude.
Falls back automatically if one is unavailable.
"""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

PLATFORM_TONE = {
    "instagram": "engaging, warm, lifestyle-focused, use 3-5 relevant emojis, 5-10 hashtags",
    "instagram_personal": "personal, authentic, conversational, use 2-4 emojis, 3-5 hashtags",
    "tiktok": "trendy, energetic, hook in first line, use Gen-Z friendly language, 3-5 hashtags",
    "facebook": "friendly, community-oriented, conversational, minimal emojis, no hashtags needed",
    "linkedin": "professional, insightful, value-driven, minimal emojis, 3 relevant hashtags",
    "linkedin_company": "brand voice, thought leadership, professional, 3 hashtags",
    "linkedin_personal": "personal brand, authentic professional, 2-3 hashtags",
    "youtube": "descriptive title and description, SEO-friendly, include keywords",
    "threads": "concise, conversational, under 500 chars, 1-2 hashtags max",
    "pinterest": "descriptive, inspiring, keyword-rich for SEO, no emojis",
    "mastodon": "informative, community-friendly, 1-2 hashtags",
    "bluesky": "concise, clever, conversational, 1-2 hashtags",
    "google_business": "professional, local business tone, call to action, no hashtags",
    "twitter": "punchy, under 280 chars, 1-2 hashtags, one emoji max",
}


def generate_caption(
    file_name: str,
    platform: str,
    tags: list[str] | None = None,
    extra_context: str = "",
) -> str:
    """Generate an AI caption for a social media post.

    Tries Gemini first, falls back to Claude, then returns a basic caption.

    Args:
        file_name: The media filename (e.g. 'summer_sale_promo.mp4')
        platform: Target platform slug (e.g. 'instagram', 'tiktok')
        tags: Lark tags on the file (used as content hints)
        extra_context: Any additional context to pass to the AI

    Returns:
        Generated caption string.
    """
    tags = tags or []
    tone = PLATFORM_TONE.get(platform, "engaging and professional")
    topic_hints = ", ".join(t for t in tags if t not in PLATFORM_TONE) or file_name.replace("_", " ").replace("-", " ")

    prompt = (
        f"Write a social media caption for {platform}.\n"
        f"Content topic hints: {topic_hints}\n"
        f"Tone/style: {tone}\n"
        f"File name: {file_name}\n"
    )
    if extra_context:
        prompt += f"Additional context: {extra_context}\n"
    prompt += "\nWrite ONLY the caption text, no explanations or quotes."

    # Try Gemini first
    caption = _try_gemini(prompt)
    if caption:
        logger.info("Caption generated by Gemini for %s/%s", platform, file_name)
        return caption

    # Fall back to Claude
    caption = _try_claude(prompt)
    if caption:
        logger.info("Caption generated by Claude for %s/%s", platform, file_name)
        return caption

    # Last resort: basic caption from filename
    logger.warning("AI caption generation failed for %s — using basic fallback", file_name)
    return _basic_caption(file_name, tags)


def _try_gemini(prompt: str) -> str | None:
    """Attempt caption generation via Google Gemini API."""
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_AI_API_KEY")
    if not api_key:
        return None
    try:
        import google.generativeai as genai  # pip install google-generativeai
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)
        return response.text.strip()
    except ImportError:
        logger.debug("google-generativeai not installed, skipping Gemini")
        return None
    except Exception as e:
        logger.warning("Gemini caption failed: %s", e)
        return None


def _try_claude(prompt: str) -> str | None:
    """Attempt caption generation via Anthropic Claude API."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    try:
        import anthropic  # pip install anthropic
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.content[0].text.strip()
    except ImportError:
        logger.debug("anthropic not installed, skipping Claude")
        return None
    except Exception as e:
        logger.warning("Claude caption failed: %s", e)
        return None


def _basic_caption(file_name: str, tags: list[str]) -> str:
    """Simple fallback caption from filename and tags."""
    name = file_name.rsplit(".", 1)[0].replace("_", " ").replace("-", " ").title()
    hashtags = " ".join(f"#{t}" for t in tags if t not in PLATFORM_TONE)
    return f"{name}\n{hashtags}".strip()
