# Generated by Django 5.1.15 on 2026-06-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("composer", "0015_per_account_status"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="LarkWatchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_token", models.CharField(max_length=200)),
                ("folder_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("poll_interval_seconds", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lark_watch_configs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "folder_token")},
            },
        ),
        migrations.CreateModel(
            name="ProcessedLarkFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_token", models.CharField(max_length=200, unique=True)),
                ("file_name", models.CharField(max_length=500)),
                ("fingerprint", models.CharField(max_length=64)),
                ("folder_token", models.CharField(max_length=200)),
                ("folder_name", models.CharField(blank=True, max_length=200)),
                ("resolved_platforms", models.JSONField(default=list)),
                ("telegram_storage", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lark_source",
                        to="composer.post",
                    ),
                ),
                (
                    "watch_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_files",
                        to="lark_sync.larkwatchconfig",
                    ),
                ),
            ],
        ),
    ]
